markdown:   kramdown
style:  minimal

name: Hyunchol(Joseph) Jun
location: Toronto, ON
job_title: Full-Stack Web Developer
github_username: hyunchol-jun
linkedin_username: hyunchol-jun
phone_number: +1 (782)234-1899
email: hyunchol.jun@gmail.com
